Added a basic endpoint to initialize user's session
genomehubs/kinfin pull request #9
Opened 2024-06-25 09:52 UTC by rohan-b-84

2024-06-25 13:05 UTC, rjchallis commented on requirements.txt
would be nice to split dependencies and move pytest into `requirements-dev.txt`. Can have `-r requirements.txt` as the first line of this file so `pip install -r requirements-dev.txt` will install everything

2024-06-25 15:52 UTC, rohan-b-84 commented on requirements.txt
done

2024-06-26 15:50 UTC, rjchallis requested changes
This is looking good! I don't know the code well enough to comment on details, so mostly comments about docstrings and ideally using logging instead of print statements.

2024-06-26 15:50 UTC, rjchallis commented on requirements-dev.txt
first line can be 
```
-r requirements.txt
```
then only pytest dep is needed to save maintaining versions in 2 files

2024-06-26 15:50 UTC, rjchallis commented on src/cli/validate.py
Ideally use a logging module for these messages

2024-06-26 15:50 UTC, rjchallis commented on src/api/__init__.py
add a docstring to describe the function

2024-06-26 15:50 UTC, rjchallis commented on src/api/endpoints.py
add a docstring to describe the function

2024-06-26 15:50 UTC, rjchallis commented on src/api/sessions.py
add docstrings

2024-06-26 15:50 UTC, rjchallis commented on src/cli/__init__.py
add a docstring to describe the function

2024-06-26 15:50 UTC, rjchallis commented on src/core/build.py
would prefer logging to print

2024-06-26 15:50 UTC, rjchallis commented on src/core/datastore.py
Would be better to replace long series of `append`s with list declaration

2024-06-26 15:50 UTC, rjchallis commented on src/core/results.py
add a docstring to describe the function

2024-06-26 15:50 UTC, rjchallis commented on src/core/utils.py
add missing docstrings

2024-06-26 15:50 UTC, rjchallis commented on src/main.py
use logging instead of print

2024-06-26 15:50 UTC, rjchallis commented on test
would prefer `.sh` suffix on shell scripts and consider moving test scripts/files to tests subdirectory

2024-08-27 13:12 UTC, rjchallis approved these changes

2024-08-27 13:13 UTC, rjchallis commented
Looks great - lets get this merged and save the full API docs for a follow up PR

2024-08-27 13:13 UTC, merged